# -*- coding: utf-8 -*-
"""kadai_015.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_zuu6x3Po_8wgAS9juoRTV7sDBgP4J0Y
"""

class Human:
    def __init__(self, name, age):
        self.name = name
        self.age = age

    def printinfo(self):
        print(f"名前: {self.name}, 年齢: {self.age}")

human = Human("samurai", 36)

human.printinfo()